admin_lalo/admin_lalo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
    url(r'^projects/', include('projects.urls')),
]


handler404 = error_404

admin_lalo/clients/urls.py
from django.conf.urls import url

from views import ShowClass
from views import LoginClass
from views import logout
from views import DashboardClass
from views import CreateClass
from views import EditSocialClass

from views import edit_password
from views import edit
from views import user_filter

app_name = 'client'

urlpatterns = [
    # url(r'^show/(?P<pk>\d+)/$', views.ShowView.as_view(), name = 'show'),
    url(r'^show/(?P<username_url>\w+)/$', ShowClass.as_view(), name = 'show'),
    url(r'^login/$', LoginClass.as_view(), name = 'login'),
    url(r'^logout/$', logout, name = 'logout'),
    url(r'^dashboard/$', DashboardClass.as_view(), name = 'dashboard'),
    url(r'^create/$', CreateClass.as_view(), name = 'create'),

    url(r'^edit/$', edit, name = 'edit'),
    url(r'^edit/password/$', edit_password, name = 'edit_password'),
    url(r'^edit/social/$', EditSocialClass.as_view(), name = 'edit_social'),
    # url(r'filter$', user_filter, name='filter'),
    url(r'filter$', user_filter, name='filter'),
]

admin_lalo/projects/urls.py
from django.conf.urls import url

from .views import CreateClass
from .views import ListClass
from .views import ShowClass
from .views import edit
from .views import ListMyProjectsClass
from .views import ListContributorsClass
from .views import add_contributor
from .views import user_contributor
from .views import delete_contributor

app_name = 'project'

urlpatterns = [
	url(r'^$',ListClass.as_view(), name='projects'),
	url(r'^mine/$',ListMyProjectsClass.as_view(), name='my_projects'),
	url(r'^create/$', CreateClass.as_view(), name = 'create'),
	url(r'^(?P<slug>[\w-]+)/$', ShowClass.as_view(), name = 'show'),
	url(r'^(?P<slug>[\w-]+)/edit/$', edit, name = 'edit'),
	url(r'^(?P<slug>[\w-]+)/contributors/$', ListContributorsClass.as_view(), name = 'contributors'),
	url(r'^(?P<slug>[\w-]+)/contributors/add/(?P<username>[\w-]+)/$', add_contributor, name='add_contributor'),
	url(r'^(?P<slug>[\w-]+)/contributors/(?P<username>[\w-]+)/$', user_contributor, name='user_contributor'),
	url(r'^(?P<slug>[\w-]+)/contributors/delete/(?P<username>[\w-]+)/$', delete_contributor, name='delete_contributor'),
]

admin_lalo/clients/models.py
from __future__ import unicode_literals
from django.db import models

from django.contrib.auth.models import User
# Create your models here.


class Client(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	job = models.CharField(max_length = 100, default = "")
	bio = models.TextField(max_length = 200, default = "")

	def __str__(self):
		return self.user.username


class SocialNetwork(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	facebook = models.URLField(blank=True)
	twitter = models.URLField(blank=True)
	github = models.URLField(blank=True)

	def __str__(self):
		return self.user.username

admin_lalo/clients/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from .models import Client
from .models import SocialNetwork


'''
Constants
'''
ERROR_MESSAGE_USER = {'required' : 'El username es requerido', 'unique' : 'El username ya se encuentra registrado', 'invalid' : 'Ingresa un username válido'}
ERROR_MESSAGE_PASSWORD = {'required' : 'El password es requerido'}
ERROR_MESSAGE_EMAIL = {'required' : 'El email es requerido', 'invalid' : 'Ingresa un correo válido'}



'''
Functions
'''
def must_be_gt(value_password):
	if len(value_password) < 5:
		raise forms.ValidationError('El password debe contener al menos 5 caracteres')




'''
Class
'''

# Los formularios en Django hay que declararlos en una clase
class LoginUserForm(forms.Form):
	username = forms.CharField(max_length=20)
	password = forms.CharField(max_length=20, widget=forms.PasswordInput())

	# Constructor
	def __init__(self, *args, **kwargs):
		super(LoginUserForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update( {'id': 'username_login', 'class': 'input_login' } )
		self.fields['password'].widget.attrs.update( {'id': 'password_login', 'class': 'input_login' } )






# Formulario basado en Modelos
class CreateUserForm(forms.ModelForm):
	username = forms.CharField(max_length=20, error_messages = ERROR_MESSAGE_USER)
	password = forms.CharField(max_length=20, widget=forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD)
	email = forms.CharField(error_messages = ERROR_MESSAGE_EMAIL)

	def __init__(self, *args, **kwargs):
		super(CreateUserForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update( {'id': 'username_create' } )
		self.fields['password'].widget.attrs.update( {'id': 'password_create' } )
		self.fields['email'].widget.attrs.update( {'id': 'email_create' } )

	# Validación de email
	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email = email).count():
			raise forms.ValidationError('El email ya existe')
		return email

	class Meta:
		model = User
		fields = ('username', 'password', 'email')





class EditUserForm(forms.ModelForm):
	username = forms.CharField(max_length=20, error_messages = ERROR_MESSAGE_USER)
	email = forms.CharField(error_messages = ERROR_MESSAGE_EMAIL)
	first_name = forms.CharField(label = 'Nombre(s)',required=False)
	last_name = forms.CharField(label='Apellidos',required=False)

	class Meta:
		model = User
		fields = ('username', 'email', 'first_name', 'last_name')

	# Validación de email
	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email = email).exclude(pk=self.instance.id).count():
			raise forms.ValidationError('El email ya existe')
		return email




class EditPasswordForm(forms.Form):
	password = forms.CharField(max_length=20, widget=forms.PasswordInput())
	new_password = forms.CharField(max_length=20, widget=forms.PasswordInput(), validators=[must_be_gt])
	repeat_password = forms.CharField(max_length=20, widget=forms.PasswordInput(), validators=[must_be_gt])

	def clean(self):
		clean_data = super(EditPasswordForm,self).clean()
		password1 = clean_data.get('new_password')
		password2 = clean_data.get('repeat_password')

		if password1 != password2:
			raise forms.ValidationError('La contraseña no coincide')

	# def clean_new_password(self):
	# 	value_password = self.cleaned_data['new_password']
	# 	if len(value_password) < 5:
	# 		raise forms.ValidationError('El password debe contener al menos 5 caracteres')
	# 	value_password



class EditClientForm(forms.ModelForm):
	job = forms.CharField(label = "Trabajo actual", required=False)
	bio = forms.CharField(label = "Biografía", widget=forms.Textarea, required=False)
	class Meta:
		model = Client
		#fields = ('bio','job')
		exclude = ['user']



class EditClientSocial(forms.ModelForm):
	class Meta:
		model = SocialNetwork
		exclude = ['user']

admin_lalo/clients/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from .models import Client
from .models import SocialNetwork

from django.shortcuts import render
from django.shortcuts import redirect
#from django.http import HttpResponse

from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.contrib.auth import update_session_auth_hash

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required

from forms import LoginUserForm
from forms import CreateUserForm
from forms import EditUserForm
from forms import EditPasswordForm
from forms import EditClientForm
from forms import EditClientSocial

from django.views.generic import View
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin


# Create your views here.

'''
	Class
'''

class ShowClass(DetailView):
	model = User
	template_name = 'client/show.html'
	slug_field = 'username' # Campo de la base de datos por el cuál se va a filtrar
	slug_url_kwarg = 'username_url' # Que de la url

# Siempre que se asocie una funcion a una url, debe recibir como parametro un request
'''
def show(request):
	return HttpResponse("Hola desde el cliente")
'''





# ----- Autenticación de Usuario ----- #
class LoginClass(View):
	form = LoginUserForm()
	message = None
	template = 'client/login.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated():
			return redirect('client:dashboard')
		return render(request, self.template,self.get_context())

	def post(self, request, *args, **kwargs):
		username = request.POST['username']
		password = request.POST['password']
		# authenticate regresa un objeto del tipo User
		user = authenticate(username = username, password = password)
		if user is not None:
			# Con esto ya podemos usar el "user" dentro de las plataformas
			login_django(request, user)
			return redirect('client:dashboard')
		else:
			self.message = "Usuario o Contraseña incorrectos"

		return render(request, self.template,self.get_context())

	def get_context(self):
		return {'form':self.form, 'message':self.message}

'''
def login(request):
	if request.user.is_authenticated():
		return redirect('client:dashboard')

	message = None
	if request.method == 'POST': # Si esta recibiendo el formulario
		username = request.POST['username']
		password = request.POST['password']

		# authenticate regresa un objeto del tipo User
		user = authenticate(username = username, password = password)
		if user is not None:
			# Con esto ya podemos usar el "user" dentro de las plataformas
			login_django(request, user)
			return redirect('client:dashboard')
		else:
			message = "Usuario o Contraseña incorrectos"

	# Instanciamos el formulario
	form = LoginForm()

	context = {
		'form' : form,
		'message' : message
	}
	return render(request, 'login.html', context)
	'''





class DashboardClass(LoginRequiredMixin, View):
	# En caso de que no esté autenticado
	login_url = 'client:login'

	def get(self, request, *args, **kwargs):
		return render(request, 'client/dashboard.html', {})

'''
@login_required(login_url = 'client:login')
def dashboard(request):
	return render(request, 'dashboard.html', {})
'''








class CreateClass(CreateView):
	success_url = reverse_lazy('client:login') # reverse_lazy retorna la url completa
	template_name = 'client/create.html'
	model = User
	# Con fields, CreateView hace un formulario para renderizar en nustro html
	# fields = ('username','email')
	form_class = CreateUserForm

	# Encriptar password
	# El método form_valid regresa el objeto
	def form_valid(self, form):
		self.object = form.save(commit = False)
		self.object.set_password(self.object.password) # Encriptar password
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

'''def create(request):
	form = CreateUserForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			# commit = False Va a impedir que se almacence en la base de datos
			user = form.save(commit = False)
			user.set_password(user.password) # Encriptar password
			user.save()
			return redirect('client:login')

	context = {
		'form' : form
	}
	return render(request, 'create.html', context)
	'''




class EditSocialClass(LoginRequiredMixin,UpdateView,SuccessMessageMixin):
	login_url = 'client:login'
	model = SocialNetwork
	template_name = 'client/edit_social.html'
	success_url = reverse_lazy('client:edit_social')
	form_class = EditClientSocial
	success_message = "Tu usuario ha sido actualizado exitósamente"

	def get_object(self, queryset = None):
		return self.get_social_instance()

	def get_social_instance(self):
		try:
			return self.request.user.socialnetwork
		except:
			return SocialNetwork(user = self.request.user)





'''
	Functions
'''

@login_required(login_url = 'client:login')
def edit_password(request):
	form = EditPasswordForm(request.POST or None)
	if request.method == 'POST':
		if form.is_valid():
			current_password = form.cleaned_data['password']
			new_password = form.cleaned_data['new_password']

			if authenticate(username = request.user.username, password = current_password):
				request.user.set_password(new_password)
				request.user.save()
				# Para que Django no nos saque de la sesión
				update_session_auth_hash(request, request.user)

				messages.success(request, 'Contraseña actualizada')
			else:
				messages.error(request, 'No es posible actualizar la contraseña')


	context = {'form' : form}
	return render(request, 'client/edit_password.html', context)



# ----- Cerrar Sesión de Usuario ----- #
@login_required(login_url = 'client:login')
def logout(request):
	logout_django(request)
	return redirect('client:login')





@login_required(login_url = 'client:login')
def edit(request):
	form_client = EditClientForm(request.POST or None, instance = client_instance(request.user))
	form_user = EditUserForm(request.POST or None, instance = request.user)
	if request.method == 'POST':
		if form_client.is_valid() and form_user.is_valid():
			form_user.save()
			form_client.save()
			messages.success(request, 'Datos actualizados correctamente')

	context = {
		'form_client' : form_client,
		'form_user' : form_user
	}

	return render(request, 'client/edit.html', context)




#----- Responder al cliente mediante un JSON -----#
# Forma 1
# from django.core import serializers	
# 	users = User.objects.filter(username__startswith=username) #Select * from users where username like '%username'
# 	# Serializar es tomar un objeto y convertirlo en un formato que se pueda enviar en http
# 	users = serializers.serialize('json',users)

# 	return HttpResponse(users,content_type='application/json')


# Forma 2
import json #Libreria nativa de Python


def user_filter(request):
	username = request.GET.get('username', '') #
	
	users = User.objects.filter(username__startswith=username) #Select * from users where username like '%username'
	users = [ user_serializer(user) for user in users ]

	
	
	return HttpResponse( json.dumps(users),
												content_type='application/json' )

def user_serializer(user):
	return {'id' : user.id, 'username' : user.username}







def client_instance(user):
	try:
		return user.client
	except:
		return Client(user = user)

admin_lalo/templates/client/create.html
{% extends "bases/base_admin.html" %}

{% block title %} Registro {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 

{% block content %} 
	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form only %}
			<input class="btn #9e9e9e grey" type="submit" value="Registrar">
		</form>
	</div>
{% endblock %} 

{% block footer %} 
	<footer>
		<p> Ya cuento con una  <a href="{% url 'client:login' %}"> cuenta	</a></p>
	</footer>
{% endblock %}

admin_lalo/templates/client/dashboard.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Dashboard {% endblock %} 

{% block scripts %} 
	{# nada por el momento #}
{% endblock %} 


{% block content %} 
	<h3>Bienvenido {{ user.username|title }}</h3>
	<a href="{% url 'client:show' user.username %}">  {{user.username}} 
	<a href="{% url 'project:my_projects'%}">  Mis proyectos </a>
{% endblock %} 

{% block footer %} {% endblock %} 

admin_lalo/templates/client/edit.html
{% extends "client/bases/edit_base.html" %}

{% block title %} Editar Cuenta {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 


{% block content %}

	<div class="collection">
	  <a href="{% url 'client:edit' %}" class="collection-item active">Perfil</a>
	  <a href="{% url 'client:edit_password' %}" class="collection-item">Password</a>
	  <a href="{% url 'client:edit_social' %}" class="collection-item">Redes Sociales</a>
  </div>


	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{# {% include "includes/_forms.html" with form=form only %} #}
			{% include "includes/_forms.html" with form=form_user %}
			{% include "includes/_forms.html" with form=form_client %}
			<input class="btn #9e9e9e grey" type="submit" value="Actualizar">
		</form>
	</div>
{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/client/edit_password.html
{% extends "client/bases/edit_base.html" %}
{% load staticfiles %}

{% block title %} Editar Password {% endblock %}

{% block scripts %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 

{% block subtitle %} Editar Password  {% endblock %}

{% block content %}

	<div class="collection">
    <a href="{% url 'client:edit' %}" class="collection-item">Perfil</a>
    <a href="{% url 'client:edit_password' %}" class="collection-item">Password</a>
    <a href="{% url 'client:edit_social' %}" class="collection-item active">Redes Sociales</a>
  </div>

	<div class="class_container_form">
		<form method="post" action="">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Actualizar">
		</form>
	</div>
{% endblock content %}

admin_lalo/templates/client/edit_social.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Editar redes sociales {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
	
{% block content %} 

	<div class="collection">
    <a href="{% url 'client:edit' %}" class="collection-item">Perfil</a>
    <a href="{% url 'client:edit_password' %}" class="collection-item">Password</a>
    <a href="{% url 'client:edit_social' %}" class="collection-item active">Redes Sociales</a>
  </div>

	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form only %}
			<input class="btn #9e9e9e grey" type="submit" value="actualizar">
		</form>
	</div>
{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/client/login.html
{% extends "bases/base_admin.html" %}

{% block title %} Admin Lalo {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 

{% block content %} 
	<div class="class_container_form">
		<form method="post" action="">
			{% csrf_token %}
				{% include "includes/_forms.html" with form=form only %}
				<input class="btn #9e9e9e grey" type="submit" value="Ingresar">
		</form>
	</div>
{% endblock %} 

{% block footer %} 
	<footer>
  	<a href="#"> Olvide mi contraseña  </a>
		<p> Crea una nueva cuenta <a href="{% url 'client:create' %}"> aqui </a></p>
	</footer>
{% endblock %}

admin_lalo/templates/client/show.html
{% load client_extras %}

<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>{{ user.username }}</title>
</head>
<body>
	<h3>Hola Usuario {{ user.username|title }} </h3>
	<p>Biografía</p>
	<p>{{ user.client.bio|truncatechars:100 }}</p>

	{% if user.socialnetwork %}
		{% for field in user.socialnetwork|list_fields %}
			{% with user.socialnetwork|get_value:field as value %}
				
				{% if value %}
					<p> {{ field }} </p>
					<p> {{ value }} </p>
				{% endif %}
				
			{% endwith %}
			
		{% endfor %}
	{% endif %}
</body>
</html>