admin_lalo/admin_lalo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
    url(r'^projects/', include('projects.urls')),
]


handler404 = error_404

admin_lalo/clients/urls.py
from django.conf.urls import url

from views import ShowClass
from views import LoginClass
from views import logout
from views import DashboardClass
from views import CreateClass
from views import EditSocialClass

from views import edit_password
from views import edit
from views import user_filter

app_name = 'client'

urlpatterns = [
    # url(r'^show/(?P<pk>\d+)/$', views.ShowView.as_view(), name = 'show'),
    url(r'^show/(?P<username_url>\w+)/$', ShowClass.as_view(), name = 'show'),
    url(r'^login/$', LoginClass.as_view(), name = 'login'),
    url(r'^logout/$', logout, name = 'logout'),
    url(r'^dashboard/$', DashboardClass.as_view(), name = 'dashboard'),
    url(r'^create/$', CreateClass.as_view(), name = 'create'),

    url(r'^edit/$', edit, name = 'edit'),
    url(r'^edit/password/$', edit_password, name = 'edit_password'),
    url(r'^edit/social/$', EditSocialClass.as_view(), name = 'edit_social'),
    # url(r'filter$', user_filter, name='filter'),
    url(r'filter$', user_filter, name='filter'),
]

admin_lalo/projects/urls.py
from django.conf.urls import url

from .views import CreateClass
from .views import ListClass
from .views import ShowClass
from .views import edit
from .views import ListMyProjectsClass
from .views import ListContributorsClass
from .views import add_contributor
from .views import user_contributor
from .views import delete_contributor

app_name = 'project'

urlpatterns = [
	url(r'^$',ListClass.as_view(), name='projects'),
	url(r'^mine/$',ListMyProjectsClass.as_view(), name='my_projects'),
	url(r'^create/$', CreateClass.as_view(), name = 'create'),
	url(r'^(?P<slug>[\w-]+)/$', ShowClass.as_view(), name = 'show'),
	url(r'^(?P<slug>[\w-]+)/edit/$', edit, name = 'edit'),
	url(r'^(?P<slug>[\w-]+)/contributors/$', ListContributorsClass.as_view(), name = 'contributors'),
	url(r'^(?P<slug>[\w-]+)/contributors/add/(?P<username>[\w-]+)/$', add_contributor, name='add_contributor'),
	url(r'^(?P<slug>[\w-]+)/contributors/(?P<username>[\w-]+)/$', user_contributor, name='user_contributor'),
	url(r'^(?P<slug>[\w-]+)/contributors/delete/(?P<username>[\w-]+)/$', delete_contributor, name='delete_contributor'),
]

admin_lalo/projects/models.py
from __future__ import unicode_literals


from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from status.models import Status
#from django.contrib.auth.models import User

from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length=50)
	description = models.TextField()
	dead_line = models.DateField()
	create_date = models.DateField(default = datetime.date.today)
	slug = models.CharField(max_length=50, default="")


	def validate_unique(self, exclude=None):
		self.slug = self.create_slug_field(self.title)
		if Project.objects.filter(slug = self.slug).exclude(pk = self.id).exists():
			raise ValidationError('Un proyecto con el mismo titulo ya se encuentra registrado.')

	def create_slug_field(self, value):
		return value.lower().replace(" ", "-")


	# def save(self,*args,**kwargs):
	# 	self.slug = self.title.replace(" ","_").lower()
	# 	self.validate_unique()
	# 	super(Project,self).save(*args,**kwargs)


	def get_id_status(self):
		return self.projectstatus_set.last().status_id

	def get_status(self):
		return self.projectstatus_set.last().status


	def user_has_permission(self, user):
		return self.projectuser_set.filter(user=user, permission_id__in=ProjectPermission.admin_permission()).count() > 0

	def __str__(self):
		return self.title





class ProjectStatus(models.Model):
	project = models.ForeignKey(Project)
	status = models.ForeignKey(Status)
	create_date = models.DateTimeField(default = timezone.now)




class ProjectPermission(models.Model):
	title = models.CharField(max_length=50)
	description = models.TextField()
	level = models.IntegerField()
	create_date = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.title

	@classmethod
	def founder_permission(cls):
		return ProjectPermission.objects.get(pk=1)

	@classmethod
	def co_founder_permission(cls):
		return ProjectPermission.objects.get(pk=2)

	@classmethod
	def contributor_permission(cls):
		return ProjectPermission.objects.get(pk=3)

	@classmethod
	def admin_permission(cls):
		return [1, 2]





class ProjectUser(models.Model):
	project = models.ForeignKey(Project, on_delete = models.CASCADE)
	user = models.ForeignKey(User)
	permission = models.ForeignKey(ProjectPermission)
	create_date = models.DateTimeField(default = timezone.now)

	def get_project(self):
		return self.project

	def is_founder(self):
		return self.permission == ProjectPermission.founder_permission()

	def valida_change_permission(self):
		if not self.is_founder():
			return True 
		return self.exists_another_founder()

	def exists_another_founder(self):
		return ProjectUser.objects.filter(project=self.project, permission=ProjectPermission.founder_permission()).exclude(user=self.user).count() > 0

admin_lalo/projects/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-


from django import forms
from .models import Project
from .models import ProjectPermission
import datetime



class ProjectForm(forms.ModelForm):
	title = forms.CharField(label = 'Titulo', required = True)
	description = forms.CharField(label = 'Descripción', required = True, widget=forms.Textarea)
	dead_line = forms.DateField(initial=datetime.date.today)

	class Meta:
		model = Project
		fields = ('title', 'description', 'dead_line')


class PermissionProject(forms.Form):
  permission = forms.ModelChoiceField(
                queryset=ProjectPermission.objects.all(),
                initial=0)

  def __init__(self, *args, **kwargs):
    super(PermissionProject, self).__init__(*args, **kwargs)
    self.fields['permission'].widget.attrs.update( {'class' : 'browser-default'} )

admin_lalo/projects/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from status.models import Status
from django.contrib.auth.models import User
from .models import Project
from .models import ProjectUser
from .models import ProjectPermission


from .forms import ProjectForm
from .forms import PermissionProject
from status.forms import StatusChoiceForm

from django.views.generic.list import ListView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy


from django.contrib import messages
from django.db import transaction


# Create your views here.
class CreateClass(LoginRequiredMixin,CreateView):
	login_url = 'client:login'
	template_name = 'project/create.html'
	model = Project
	form_class = ProjectForm

	# Transaccon a la base de datos, si alguno no se puede guardar, hace un rollback a las demas tablas
	@transaction.atomic
	def create_objects(self):
		self.object.save()
		self.object.projectstatus_set.create( status = Status.get_default_status() )
		self.object.projectuser_set.create(user= self.request.user,
																			permission=ProjectPermission.founder_permission() )

	def form_valid(self, form):
		self.object = form.save(commit = False)
		# Indicar que le pertenece al usuario logueado
		# self.object.user = self.request.user
		self.create_objects()
		return HttpResponseRedirect( self.get_url_project() )


	def get_url_project(self):
		return reverse_lazy('project:show', kwargs = {'slug' : self.object.slug} )

		


class ListClass(LoginRequiredMixin, ListView):
	login_url = 'client:login'
	template_name = 'project/index.html'

	def get_queryset(self):
		return Project.objects.all()


class ListMyProjectsClass(LoginRequiredMixin, ListView):
	login_url = 'client:login'
	template_name = 'project/mine.html'

	def get_queryset(self):
		return ProjectUser.objects.filter(user = self.request.user)





class ListContributorsClass(ListView):
	template_name = 'project/contributors.html'

	def get_queryset(self):
		self.project = get_object_or_404(Project, slug=self.kwargs['slug'])
		return ProjectUser.objects.filter(project=self.project)

	def get_context_data(self, **kwargs):
		context = super(ListContributorsClass, self).get_context_data(**kwargs)
		context['project'] = self.project
		return context






class ShowClass(DetailView):
	model = Project
	template_name = 'project/show.html'

	def get_context_data(self, **kwargs):
		context = super(ShowClass, self).get_context_data(**kwargs)
		if not self.request.user.is_anonymous():
			context['has_permission'] = self.object.user_has_permission(self.request.user)

		return context




"""
Functions
"""
def admin_only(function):  
	def wrap(request, *args, **kwargs):
	  project = get_object_or_404(Project,slug=kwargs['slug']) #Encontrar el usuario
	  if not project.user_has_permission(request.user): #Verificar los permisos
	  	lazy = reverse_lazy('project:show', kwargs={'slug': project.slug})
	  	return HttpResponseRedirect(lazy)
	  return function(request, *args, **kwargs)
	return wrap






@login_required(login_url='client:login')
@admin_only
def edit(request, slug=''):
	project = get_object_or_404(Project, slug=slug)
	form_project = ProjectForm(request.POST or None, instance = project)
	forms_status = StatusChoiceForm(request.POST or None, initial = {'status': project.get_id_status()})

	if request.method == 'POST':
		if form_project.is_valid() and forms_status.is_valid():
			selection_id = forms_status.cleaned_data['status'].id

			form_project.save()
			if selection_id != project.get_id_status():
				project.projectstatus_set.create( status_id = selection_id)
			messages.success(request, 'Datos actualizados correctamente')
	context = {
		'form_project': form_project,
		'forms_status': forms_status
	}
	return render(request, 'project/edit.html', context)




@login_required(login_url='client:login')
@admin_only
def add_contributor(request, slug, username):
	project = get_object_or_404(Project, slug=slug)
	user = get_object_or_404(User, username=username)

	if not project.projectuser_set.filter(user=user).exists():
		project.projectuser_set.create(user=user,permission=ProjectPermission.contributor_permission())

	# if not project.projectuser_set.filter(user=user).exists():
	# 	project.projectuser_set.create(user=user,
	# 																permission=ProjectPermission.contributor_permission())

	return redirect('project:contributors', slug=project.slug)





@login_required(login_url='client:login')
def user_contributor(request, slug, username):
	project = get_object_or_404(Project, slug=slug)
	user = get_object_or_404(User, username=username)
	permission = get_object_or_404(ProjectUser, user=user, project=project) # Permiso que tiene actualmente el usuario

	form = PermissionProject(request.POST or None,
													initial={'permission' : permission.permission_id })

	if request.method == 'POST' and form.is_valid():
		selection_id = form.cleaned_data['permission'].id #Obtener el id que selecciono el usuario
		if selection_id != permission.id and permission.valida_change_permission(): # Si el id es diferente al que ya tenia
			permission.permission_id = selection_id
			permission.save()
			messages.success(request, 'Datos actualizados correctamente.')

	context = {
		'project' : project,
		'user' : user,
		'has_permission' : project.user_has_permission(request.user),
		'form' : form,
	}

	return render(request, 'project/contributor.html', context)




@login_required(login_url='client:login')
@admin_only
def delete_contributor(request, slug, username):
	project = get_object_or_404(Project, slug=slug)
	user = get_object_or_404(User, username=username)

	project_user = get_object_or_404(ProjectUser, user=user, project=project)
	if not project_user.is_founder():
		project_user.delete()
	
	return redirect('project:contributors', slug=project.slug)

admin_lalo/templates/project/contributor.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Colaborador {% endblock %} 

{% block scripts %}
  {% load staticfiles %}
     <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
  
{% block content %} 
    <h4>Colaborador {{ user.username }}</h4>
    {% if has_permission %}
      <div class = "class_container_form">
        <form method="POST", action="">
          {% csrf_token %}
          {% include "includes/_forms.html" with form=form only %}
          <input class="btn #9e9e9e grey" type="submit" value="Actualizar">
        </form>
      </div>

      <br>
      <br>

      <a href="{% url 'project:delete_contributor' project.slug user.username %}">Eliminar de colaboradores</a>
    {% endif %}
    

{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/contributors.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Colaboradores {% endblock %} 

{% block scripts %}
  {% load staticfiles %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
   <script type="text/javascript" src="{% static 'js/search_user.js' %}"></script>
{% endblock %} 
  
{% block content %} 
  
    <h4>Colaboradores!</h4>
    {% for user in object_list%}
      <p> {{ user.user }} Permiso: {{ user.permission }}</p>
      <a href="{% url 'project:user_contributor' project.slug user.user.username %}">Ver</a>
    {% endfor %}


    <form id="search-user-form" method="GET" action="{% url 'client:filter' %}">
      <input type="text" name="username">
      <input type="submit" value="Buscar">
    </form>



    <div id="ajax-result">
      <ul>
        <!-- Aqui colocaremos los resultados -->
      </ul>  
    </div>




{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/create.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Nuevo Proyecto {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
	
{% block content %} 
	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form only %}
			<input class="btn #9e9e9e grey" type="submit" value="crear">
		</form>
	</div>
{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/edit.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Editar Proyecto {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
	
{% block content %} 

	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form_project only %}
			{% include "includes/_forms.html" with form=forms_status only %}
			<input class="btn #9e9e9e grey" type="submit" value="actualizar">
		</form>
	</div>

{% endblock %} 
{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/index.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Proyectos {% endblock %} 

{% block scripts %}
  {% load staticfiles %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
  
{% block content %} 
  
  {% for project in object_list %}
    <a href="{% url 'project:show' project.slug %}"> {{ project.title }} </a>
  {% endfor %}

{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/mine.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Mis Proyectos {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
	
{% block content %}
	<a href="{% url 'project:create' %}"> Crear proyecto</a>

	{% for project_user in object_list %}
		{% with project_user.get_project as project %}
			<a href="{% url 'project:show' project.slug %}"> {{ project.title }} </a>
		{% endwith %}
	{% endfor %}
	
{% endblock %} 

{% block footer %} 

{% endblock %} 

admin_lalo/templates/project/show.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} {{ project.title }} {% endblock %} 

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" /> 
{% endblock %} 
	
{% block content %} 

	<h4>{{ project.title }}</h4>
    
  {% if has_permission %}
    <a href="{% url 'project:edit' project.slug %}"> Editar </a>
  {% endif %}

{% endblock %} 

{% block footer %} 

{% endblock %} 